name: praksa
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.6
  flutter_dotenv: ^5.0.2
  lastfm: ^0.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/


flutter_native_splash:
  color: "3234a8"
  #background_image: "assets/splash.png"
  #image: "assets/splash.png"

  android_12:
    color: "42a5f5"
    #image: "assets/splash.png"
    #android_gravity: center
